{{- if and .Values.agent (not .Values.preflight.enabled) .Values.prometheus.enabled }}
---
{{- if .Values.prometheus.serviceMonitor.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: cilium-agent
  namespace: {{ .Release.Namespace }}
  labels:
    k8s-app: cilium
spec:
  clusterIP: None
  type: ClusterIP
  selector:
    k8s-app: cilium
  ports:
  - name: metrics
    port: {{ .Values.prometheus.port }}
    protocol: TCP
    targetPort: prometheus
  - name: envoy-metrics
    port: {{ .Values.proxy.prometheus.port }}
    protocol: TCP
    targetPort: envoy-metrics
{{- else if .Values.proxy.prometheus.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: cilium-agent
  namespace: {{ .Release.Namespace }}
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: {{ .Values.proxy.prometheus.port | quote }}
  labels:
    k8s-app: cilium
spec:
  clusterIP: None
  type: ClusterIP
  selector:
    k8s-app: cilium
  ports:
  - name: envoy-metrics
    port: {{ .Values.proxy.prometheus.port }}
    protocol: TCP
    targetPort: envoy-metrics
{{- end }}
{{- end }}
{{- if and .Values.hubble.enabled (hasKey .Values.hubble "listenPort") (hasKey .Values.hubble "peerServicePort") }}
---
apiVersion: v1
kind: Service
metadata:
  name: hubble-peer
  namespace: {{ .Release.Namespace }}
  labels:
    k8s-app: cilium
spec:
  selector:
    k8s-app: cilium
  ports:
  - name: peer-service
    port: {{ .Values.hubble.peerServicePort }}
    protocol: TCP
    targetPort: {{ .Values.hubble.listenPort }}
{{- if semverCompare ">=1.22-0" .Capabilities.KubeVersion.GitVersion }}
  internalTrafficPolicy: Local
{{- end }}
{{- end }}
